### ISSUE TITLE
Not able to customize

### ISSUE THREAD

**Issue by 9jaswitch** [kevquirk/quirk-wordpress-theme#2]
When I installed the theme and check for a live preview, I found out I cant change the site identity. 

I cant remove the image icon and the text under it . It people can use it 

FYI- I'm not a developer but I use WP for my blog

**Comment by kevquirk** [comment]
This is really a theme for developers. I haven't integrated any backend WP admin features, like changing the logos etc. It's all done in code.

**Comment by kevquirk** [comment]
If you want to change "Kev Quirk" to something else, it's on lines 41 and 45 of `header.php`
